const TEXT =
  '*** INITIATING SEQUENCE // NO SIGNAL DETECTED IN SECTOR 4 // ARCHIVE EXPANSION IN PROGRESS // DATA LOSS ACCEPTABLE // STRUCTURAL INTEGRITY COMPROMISED // RECALIBRATING GRID *** INITIATING SEQUENCE // NO SIGNAL DETECTED IN SECTOR 4 // ARCHIVE EXPANSION IN PROGRESS // DATA LOSS ACCEPTABLE // STRUCTURAL INTEGRITY COMPROMISED // RECALIBRATING GRID ***';

export default function MarqueeFooter() {
  return (
    <footer className="marquee-footer">
      <div className="marquee-content">{TEXT}</div>
    </footer>
  );
}
